[management]
mgmt01 ansible_host=192.168.100.16 ansible_user=firdauz ansible_connection=local

[managed_servers]
terraform-test ansible_host=192.168.100.19 ansible_user=firdazer

[k3s_control_plane]
k3s-cp01 ansible_host=192.168.100.31 ansible_user=firdazer

[k3s_workers]
k3s-w01 ansible_host=192.168.100.32 ansible_user=firdazer

[k3s_cluster:children]
k3s_control_plane
k3s_workers
